name: Make a suggestion
description: Have a suggestion of any kind? this is the place.
title: "[Suggestion] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug with Terrastorage!  
        Before submitting, please make sure to read the [Feedback & Support](https://github.com/TimVincii/Terrastorage/#feedback--support) section to understand response times and other important information.
  - type: textarea
    attributes:
      label: Description
      description: Describe your idea.
    validations:
      required: true